# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 495b74a9b3b4de070bbaec8d5379dd78c6cfcc97f5bc11b2414e8ac3606a3109af72761506d033882e149b030586f905adb76dd82b13ddd998feb26b9df5c081

test:
  secret_key_base: f4b41e1fddf562b145316a9b0840d5f7b6451aa3f5528715aa1475a8f174e37aade720eca5e122c3c9ad18f0ac0693d41b1196a0ad0e6d0b01ea706cf6528796

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
